/*
 * MATLAB Compiler: 3.0
 * Date: Tue Jul 12 11:03:59 2005
 * Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on"
 * "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O"
 * "array_indexing:on" "-O" "optimize_conditionals:on" "-B" "sgl" "-m" "-W"
 * "main" "-L" "C" "-t" "-T" "link:exe" "-h" "libmmfile.mlib" "-W" "mainhg"
 * "libmwsglm.mlib" "wavecontrol.m" 
 */
#include "delsq.h"
#include "libmatlbm.h"
static mxArray * _mxarray0_;
static mxArray * _mxarray1_;
static mxArray * _mxarray2_;

void InitializeModule_delsq(void) {
    _mxarray0_ = mclInitializeDouble(4.0);
    _mxarray1_ = mclInitializeDouble(-1.0);
    _mxarray2_ = mclInitializeDouble(1.0);
}

void TerminateModule_delsq(void) {
    mxDestroyArray(_mxarray2_);
    mxDestroyArray(_mxarray1_);
    mxDestroyArray(_mxarray0_);
}

static mxArray * Mdelsq(int nargout_, mxArray * G);

_mexLocalFunctionTable _local_function_table_delsq
  = { 0, (mexFunctionTableEntry *)NULL };

/*
 * The function "mlfDelsq" contains the normal interface for the "delsq"
 * M-function from file "c:\matlab6p5\toolbox\matlab\demos\delsq.m" (lines
 * 1-35). This function processes any input arguments and passes them to the
 * implementation version of the function, appearing above.
 */
mxArray * mlfDelsq(mxArray * G) {
    int nargout = 1;
    mxArray * D = NULL;
    mlfEnterNewContext(0, 1, G);
    D = Mdelsq(nargout, G);
    mlfRestorePreviousContext(0, 1, G);
    return mlfReturnValue(D);
}

/*
 * The function "mlxDelsq" contains the feval interface for the "delsq"
 * M-function from file "c:\matlab6p5\toolbox\matlab\demos\delsq.m" (lines
 * 1-35). The feval function calls the implementation version of delsq through
 * this function. This function processes any input arguments and passes them
 * to the implementation version of the function, appearing above.
 */
void mlxDelsq(int nlhs, mxArray * plhs[], int nrhs, mxArray * prhs[]) {
    mxArray * mprhs[1];
    mxArray * mplhs[1];
    int i;
    if (nlhs > 1) {
        mlfError(
          mxCreateString(
            "Run-time Error: File: delsq Line: 1 Column: 1 The function \"delsq"
            "\" was called with more than the declared number of outputs (1)."),
          NULL);
    }
    if (nrhs > 1) {
        mlfError(
          mxCreateString(
            "Run-time Error: File: delsq Line: 1 Column: 1 The function \"delsq"
            "\" was called with more than the declared number of inputs (1)."),
          NULL);
    }
    for (i = 0; i < 1; ++i) {
        mplhs[i] = NULL;
    }
    for (i = 0; i < 1 && i < nrhs; ++i) {
        mprhs[i] = prhs[i];
    }
    for (; i < 1; ++i) {
        mprhs[i] = NULL;
    }
    mlfEnterNewContext(0, 1, mprhs[0]);
    mplhs[0] = Mdelsq(nlhs, mprhs[0]);
    mlfRestorePreviousContext(0, 1, mprhs[0]);
    plhs[0] = mplhs[0];
}

/*
 * The function "Mdelsq" is the implementation version of the "delsq"
 * M-function from file "c:\matlab6p5\toolbox\matlab\demos\delsq.m" (lines
 * 1-35). It contains the actual compiled code for that M-function. It is a
 * static function and must only be called from one of the interface functions,
 * appearing below.
 */
/*
 * function D = delsq(G)
 */
static mxArray * Mdelsq(int nargout_, mxArray * G) {
    mexLocalFunctionTable save_local_function_table_
      = mclSetCurrentLocalFunctionTable(&_local_function_table_delsq);
    mxArray * D = NULL;
    mxArray * q = NULL;
    mxArray * Q = NULL;
    mxArray * k = NULL;
    mxArray * s = NULL;
    mxArray * j = NULL;
    mxArray * i = NULL;
    mxArray * p = NULL;
    mxArray * n = NULL;
    mxArray * m = NULL;
    mclCopyArray(&G);
    /*
     * %DELSQ  Construct five-point finite difference Laplacian.
     * %   delsq(G) is the sparse form of the two-dimensional,
     * %   5-point discrete negative Laplacian on the grid G.
     * %   The grid G can be generated by NUMGRID or NESTED.
     * %
     * %   See also NUMGRID, DEL2, DELSQDEMO.
     * 
     * %   C. Moler, 7-16-91.
     * %   Copyright 1984-2002 The MathWorks, Inc. 
     * %   $Revision: 5.7 $  $Date: 2002/04/08 20:04:39 $
     * 
     * [m,n] = size(G);
     */
    mlfSize(mlfVarargout(&m, &n, NULL), mclVa(G, "G"), NULL);
    /*
     * 
     * % Indices of interior points
     * p = find(G);
     */
    mlfAssign(&p, mlfFind(NULL, NULL, mclVa(G, "G")));
    /*
     * 
     * % Connect interior points to themselves with 4's.
     * i = G(p);
     */
    mlfAssign(&i, mclArrayRef1(mclVa(G, "G"), mclVv(p, "p")));
    /*
     * j = G(p);
     */
    mlfAssign(&j, mclArrayRef1(mclVa(G, "G"), mclVv(p, "p")));
    /*
     * s = 4*ones(size(p));
     */
    mlfAssign(
      &s,
      mclMtimes(
        _mxarray0_,
        mlfOnes(mlfSize(mclValueVarargout(), mclVv(p, "p"), NULL), NULL)));
    /*
     * 
     * % for k = north, east, south, west
     * for k = [-1 m 1 -m]
     */
    {
        mclForLoopIterator viter__;
        for (mclForStart(
               &viter__,
               mlfHorzcat(
                 _mxarray1_,
                 mclVv(m, "m"),
                 _mxarray2_,
                 mclUminus(mclVv(m, "m")),
                 NULL),
               NULL,
               NULL);
             mclForNext(&viter__, &k);
             ) {
            /*
             * % Possible neighbors in k-th direction
             * Q = G(p+k);
             */
            mlfAssign(
              &Q,
              mclArrayRef1(
                mclVa(G, "G"), mclPlus(mclVv(p, "p"), mclVv(k, "k"))));
            /*
             * % Index of points with interior neighbors
             * q = find(Q);
             */
            mlfAssign(&q, mlfFind(NULL, NULL, mclVv(Q, "Q")));
            /*
             * % Connect interior points to neighbors with -1's.
             * i = [i; G(p(q))];
             */
            mlfAssign(
              &i,
              mlfVertcat(
                mclVv(i, "i"),
                mclArrayRef1(
                  mclVa(G, "G"), mclArrayRef1(mclVv(p, "p"), mclVv(q, "q"))),
                NULL));
            /*
             * j = [j; Q(q)];
             */
            mlfAssign(
              &j,
              mlfVertcat(
                mclVv(j, "j"),
                mclArrayRef1(mclVv(Q, "Q"), mclVv(q, "q")),
                NULL));
            /*
             * s = [s; -ones(length(q),1)];
             */
            mlfAssign(
              &s,
              mlfVertcat(
                mclVv(s, "s"),
                mclUminus(
                  mlfOnes(
                    mlfScalar(mclLengthInt(mclVv(q, "q"))), _mxarray2_, NULL)),
                NULL));
        /*
         * end
         */
        }
        mclDestroyForLoopIterator(viter__);
    }
    /*
     * D = sparse(i,j,s);
     */
    mlfAssign(
      &D,
      mlfSparse(mclVv(i, "i"), mclVv(j, "j"), mclVv(s, "s"), NULL, NULL, NULL));
    mclValidateOutput(D, 1, nargout_, "D", "delsq");
    mxDestroyArray(m);
    mxDestroyArray(n);
    mxDestroyArray(p);
    mxDestroyArray(i);
    mxDestroyArray(j);
    mxDestroyArray(s);
    mxDestroyArray(k);
    mxDestroyArray(Q);
    mxDestroyArray(q);
    mxDestroyArray(G);
    mclSetCurrentLocalFunctionTable(save_local_function_table_);
    return D;
}
